urls.py
from django.conf.urls.defaults import patterns, include, url
from customforms.views import *
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'LU_customforms.views.home', name='home'),
    # url(r'^LU_customforms/', include('LU_customforms.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
	(r'^$',landing),
	(r'^submit/$',onSubmit),
	(r'^list/$',formList),
	(r'^clear/$',clearTables),
	(r'^success/(\d{1,10})/$',onSuccess),
	(r'^display/(\d{1,10})/$', displayForm),
	(r'^results/(\d{1,10})/$', showResults),
)

old_files/models.py
from django.db import models

class MyUser(models.Model):
	name=models.CharField(max_length=15, default="User")

class Form(models.Model):
	title=models.CharField(max_length=30,default="Form")
	
class Question(models.Model):
	form=models.ForeignKey(Form)
	question=models.CharField(max_length=60)
	ques_type=models.CharField(max_length=15)
	required=models.CharField(max_length=2)
	
class Option(models.Model):
	#Stores options for a particular multiple-choice type question
	
	question=models.ForeignKey(Question)
	opt=models.CharField(max_length=30)
	
	
		
class Responses(models.Model):
	question=models.ForeignKey(Question)
	resp=models.CharField(max_length=50,null=True,blank=True)	
	form=models.ForeignKey(Form)
	myuser=models.ForeignKey(MyUser)

templates/form.html
<html>
	<head>
		<title>Custom Forms Example</title>
		
		<link rel="stylesheet" type="text/css" href="/static/stylesheets/style.css">
	</head>
	
	<body>
		<div class="wrapper">
			
			<div class="form_preview">
				<h2>Form</h2>
				<hr />
				<p class="help_text">Fields marked * are <strong>required</strong></p>
				<br />
				
				<form action="" method="POST">
					{% csrf_token %}
					{{ form.as_p }}
					<br />
					<input type="submit" value="Submit" />
				</form>	
				
			</div>
			
		</div>	
	</body>
</html>			

templates/home.html
<html>
<head>
<title>Facebook</title>
</head>
<body>
<p>Hello. {{username}}</p>
<p> Your email is {{user_email}}</p>
<p>
{% for item in photos_src %}
<img src="{{item}}"/><br/><br/>
{% endfor %}
</p>


</body>
</html>

templates/index.html
<html>
	<head>
		<title>Custom Forms Example</title>
		<script src="/static/js/jquery-1.5.1.min.js"></script>
		<script src="/static/js/jquery-ui-1.8.13.custom.min.js"></script>
		<script src="/static/js/json2.js"></script>
		<script src="/static/js/custom_form.js"></script> 
		 
		<link rel="stylesheet" type="text/css" href="/static/stylesheets/style.css">
	</head>
	
	<body>
		<div class="wrapper">
			
			<div class="preview_area">
				<h2 id='form_title'>Form Preview</h2>
				<hr />
				<br /><br/>
				<div class="form_preview"></div>
				<!--<input type="button" value="Create form" id="sbmt"/>-->
			</div>
			
			<div class="form_toolbox">
				<div id="toolbox_header"> 
					<ul>
						<li>Form Information</li>
						<li>Form Fields</li>
					</ul>
				</div>
				
				<div id="toolbox_content">
					<!--
					<p>Give your form a title-</p>
					<form>
						<input type="text" id="input_title" />
						<input type="button" id="button_title" value="Update"/>
					</form>	
					<br/>
					-->
				
					<div id="field_selector">
						<br/>
						<table border="0">
							<tr>
								<td>
									<p>Field Category</p>
								</td>
								<td>
									<select id="cat_selector" onChange="onSelectCategory($('#cat_selector').attr('value'))">
										<option value="Generic" selected="selected">Generic</option>
										<option value="Personal">Personal Information</option>
										<option value="Program">Dummy Program</option>
									</select>
								</td>
							</tr>
							<tr>
								<td>
									<p>Field</p>
								</td>
								<td>
									<select id="elem_selector" onChange="onSelectElem($('#elem_selector').attr('value'))">
										
									</select>
								</td>
							</tr>		
						</table>					
					</div>
					
					<div id="field_properties">
						
						<p class="toolboxText">Field label</p>
						<textarea name="question" id="id_question" rows=4 cols=30></textarea>
						<p class="toolboxText">Instructions for user</p>
						<textarea name="instructions" id="id_instructions" rows=4 cols=40></textarea>
						<p class="toolboxText">Required&nbsp;
							<input type="checkbox" id="id_required" name="required" /></p><br/>
						<form id="elem_properties">
							<div id="multi_options"></div>
						</form>
						<div id="other_options"></div>		
						<br/><br/>
						<input type="button" id="button_add" value="Add to Form"/> &nbsp;&nbsp;
					</div>
				</div>
							
			</div>		
		</div>	
	</body>
</html>			

templates/index1.html
<html>
<head>
<title>Facebook</title>
</head>
<body>
	<p> new test </p>
<a href="{{url}}">Login to Facebook</a>
</body>
</html>

templates/list.html
<html>
	<head>
		<title>Custom Forms Example</title>
		
		<link rel="stylesheet" type="text/css" href="/static/stylesheets/style.css">
	</head>
	
	<body>
		<div class="wrapper">
			
			<div class="form_preview">
				<h2>Created Forms</h2>
				<hr />
				<p class="help_text">Pick a form to fill out</p>
				<br />
				{% for form in forms %}
					{% if form.active %}
					<a href='/display/{{form.id}}/'>{{form.title}}</a>
					<br/>
					{% endif %}
				{% endfor %}	
				
			</div>
			
		</div>	
	</body>
</html>			

templates/question.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{username}}</title>  
  
</head>
<body>
<br/>	
   <div><table>
    {% if form_display %}
   <form action="" name="post_question" method="POST">
	Question: <br/>
	<textarea name="question"></textarea><br/>
	
	{% for friend in friends %}
		<tr>
			<td><input type="checkbox" name="user_id" value="{{friend.id}}"/></td>
			<td><img src="http://graph.facebook.com/{{friend.id}}/picture"/></td>
			<td>{{friend.name}}</td>
		</tr>
		
	{% endfor %}  

	<input type="submit" value="Post your question"/>
	</form>	
	</table>
	{% else %}
	<p>{{question}} was successfully posted.</p>
	{% endif %}
     
    </div>    
</body>
</html>

templates/results.html
<html>
	<head>
		<title>Custom Forms Example</title>
		
		<link rel="stylesheet" type="text/css" href="/static/stylesheets/style.css">
		
		
	</head>
	
	<body>
		<div class="wrapper">
			
			<div class="form_preview">
				<h2>Results</h2>
				<hr />
				<p>Results for <strong>{{ title }}</strong></p>
				<br />
				<div class="results">
					<table id="tab_res">
						<tr >
							{% for question in questions %}
							<th width="100px">{{question}}</th>
							{% endfor %}
						</tr>
						{% for response in responses %}
							<tr>
								{% for answer in response %}
									<td width="100px">{{answer}}</td>
								{% endfor %}
							</tr>
						{%endfor%}			
					</table>
				</div>
			</div>
			
		</div>	
	</body>
</html>			

templates/success.html
<html>
	<head>
		<title>Custom Forms Example</title>
		
		<link rel="stylesheet" type="text/css" href="/static/stylesheets/style.css">
	</head>
	
	<body>
		<div class="wrapper">
			
			<div class="form_preview">
				<h2>Thank you</h2>
				<hr />
				<p> Click <a href='/results/{{form_id}}/'>here</a> to view results for this form</p>
			</div>
			
		</div>	
	</body>
</html>			